Add max bandwidth api in Android sdk
jellyfish-dev/membrane-webrtc-android pull request #8
Opened 2022-09-09 18:39 UTC by graszka22

2022-09-26 17:06 UTC, mickel8 requested changes

2022-09-26 17:06 UTC, mickel8 commented on MembraneRTC/src/main/java/org/membraneframework/rtc/MembraneRTC.kt
> +    public fun setTrackBandwidth(trackId: String, bandwidthLimit: TrackBandwidthLimit) {
To be compliant with js API this should be `TrackBandwidthLimit.BandwidthLimit`

2022-09-27 11:57 UTC, graszka22 commented on MembraneRTC/src/main/java/org/membraneframework/rtc/media/VideoParameters.kt
> +public data class VideoParameters(val dimensions: Dimensions, val maxBitrate: TrackBandwidthLimit, val maxFps: Int, val simulcastConfig: SimulcastConfig = SimulcastConfig()) {
Yes, it's used but not here. Here `simulcastConfig` is a field in the class, not only an argument in constructor (see here how data class works in Kotlin: https://kotlinlang.org/docs/data-classes.html). We're accessing it later like this: `localTrack.videoParameters.simulcastConfig`

2022-09-27 13:17 UTC, mickel8 commented on MembraneRTC/src/main/java/org/membraneframework/rtc/media/VideoParameters.kt
> +public data class VideoParameters(val dimensions: Dimensions, val maxBitrate: TrackBandwidthLimit, val maxFps: Int, val simulcastConfig: SimulcastConfig = SimulcastConfig()) {
Oh, I see, thank you!

2022-09-27 13:24 UTC, mickel8 approved these changes
Nicely done! :slightly_smiling_face:

2022-09-27 16:30 UTC, merged